let express = require("@runkit/runkit/express-endpoint/1.0.0");
const app = express(exports);

app.get("/", (req, res) => {
exports.endpoint = function(req, res) {
  let decoded = "";
    if(req.query && req.query.data) {
        decoded = `
                <pre>${decode(req.query.data)}</pre>
                    `;
                      }
                        else {
                            decoded = `
                                    <p><strong>Examples</strong></p>
                                            <p>Copy the packet from, e.g., <code>"data": "ADFGUkFEshgAdAoAAACyGADXQ5rzpZs="</code> in the gateway's log.</p>
                                                    <ul>
                                                              <li><a href="?data=ANwAANB%2B1bNwHm/t9XzurwDIhgMK8sk=">Join Request <code>ANwAANB+1bNwHm/t9XzurwDIhgMK8sk=</code></a></li>:
                                                                        <li><a href="?data=IIE/R/UI/6JnC24j4B%2BEueJdnEEV8C7qCz3T4gs%2BypLa">Join Accept <code>IIE/R/UI/6JnC24j4B+EueJdnEEV8C7qCz3T4gs+ypL</code></a></li>
                                                                                  <li><a href="?data=QCkuASaAAAAByFaF53Iu%2BvzmwQ==">Uplink <code>QCkuASaAAAAByFaF53Iu+vzmwQ==</code></a></li>
                                                                                            <li><a href="?data=YCkuASYgAwDQNni9">Downlink <code>YCkuASYgAwDQNni9</code></a></li>
                                                                                                    </ul>
                                                                                                        `;
                                                                                                          }

                                                                                                            res.setHeader("Content-Type", "text/html");
                                                                                                              res.send(`
                                                                                                              <!doctype html>
                                                                                                              <html lang=en>
                                                                                                              <head>
                                                                                                                <meta charset=utf-8>
                                                                                                                  <meta name="viewport" content="width=device-width, initial-scale=1">
                                                                                                                    <title>LoRaWAN packet decoder</title>
                                                                                                                      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
                                                                                                                      </head>
                                                                                                                      <body>
                                                                                                                      <div class="container-fluid">
                                                                                                                        <div class="row">
                                                                                                                            <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1">
                                                                                                                                  <h1>LoRaWAN packet decoder</h1>
                                                                                                                                        <p class="lead">A frontend towards <a href="https://github.com/anthonykirby/lora-packet">lora-packet</a>.</p>      
                                                                                                                                              <div class="row">
                                                                                                                                                      <form>
                                                                                                                                                                <div class="col-sm-10">
                                                                                                                                                                            <label for="data">Base64 or Hex-encoded packet ${req.query.data ? '(<a href="?">examples</a>)' : ''}</label>
                                                                                                                                                                                        <input id="data" name="data" class="form-control input-lg" type="text" placeholder='Base64 or Hex-encoded packet' value="${req.query.data ? req.query.data : ''}">
                                                                                                                                                                                                  </div>
                                                                                                                                                                                                            <div class="hidden-xs col-sm-2">
                                                                                                                                                                                                                        <label for="submit">&nbsp;</label>
                                                                                                                                                                                                                                    <button id="submit" class="btn btn-default btn-lg col-sm-12" type="submit">Decode</button>
                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                      </form>
                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                  <div class="row">&nbsp;</div>
                                                                                                                                                                                                                                                                        <div class="row">
                                                                                                                                                                                                                                                                                <div class="col-xs-12">
                                                                                                                                                                                                                                                                                          ${decoded}
                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                              <div class="row">
                                                                                                                                                                                                                                                                                                                      <div class="col-sm-12">
                                                                                                                                                                                                                                                                                                                                <p>Note that erroneous packets are likely to show incorrect results: <a href="https://github.com/anthonykirby/lora-packet">lora-packet</a> can also validate the packet's integrity and decrypt the payload if you know the node's secrets. Or to install it as a command line utility:</p>
                                                                                                                                                                                                                                                                                                                                          <ul>
                                                                                                                                                                                                                                                                                                                                                      <li><a href="https://docs.npmjs.com/getting-started/installing-node">install Node.js and npm</a></li>
                                                                                                                                                                                                                                                                                                                                                                  <li>run: <code>npm install -g lora-packet</code></li>
                                                                                                                                                                                                                                                                                                                                                                              <li>run: <code>lora-packet-decode --base64 ADFGUkFEshgAdAoAAACyGADXQ5rzpZs=</code><br/>or <code>lora-packet-decode --hex 003146524144B21800740A000000B21800D7439AF3A59B</code> (beware that removing leading zeroes affects proper decoding)</li>
                                                                                                                                                                                                                                                                                                                                                                                        </ul>
                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                            </body>
                                                                                                                                                                                                                                                                                                                                                                                                            </html>
                                                                                                                                                                                                                                                                                                                                                                                                              `);
                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                              app.get("/:data", (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                res.setHeader("Content-Type", "text/plain");
                                                                                                                                                                                                                                                                                                                                                                                                                  res.send(decode(req.params.data) + "\nDecoded using https://github.com/anthonykirby/lora-packet");
                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                  // RunKit will print the last value; nothing to see here.
                                                                                                                                                                                                                                                                                                                                                                                                                  let dummy = "";
